name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Change to Website Directory
      run: cd mod5-pon1/my-website

    - name: Install Dependencies
      run: |
        cd mod5-pon1/my-website
        npm install

    - name: Build Website
      run: |
        cd mod5-pon1/my-website
        npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: mod5-pon1/my-website/build # Adjust this to the correct build directory
        token: ${{ secrets.GITHUB_TOKEN }}
